version: "2"

services:
  dev:
    build: .
    volumes:
      - ./:/code
    tty: true
    command: bash
    working_dir: /code

  ci:
    build: .
    image: keboola/keboola/php-utils
    command: bash
